# Generated by Django 3.1.14 on 2022-09-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
